### ISSUE TITLE
Exception on Payee Column

### ISSUE THREAD

**Issue by briviere** [slashdotdash/node-ledger-import#1]
Any idea why it is failing on the Payee column option?

ledger-import -f Checking_2015_01.csv  -l personal.dat -v --date-column 1 --payee-column 3 
/usr/local/lib/node_modules/ledger-import/lib/filters/transaction/extract-amount.js:58
  if (!options.column && !options.columns) {
              ^
TypeError: Cannot read property 'column' of undefined
    at Object.extractAmount (/usr/local/lib/node_modules/ledger-import/lib/filters/transaction/extract-amount.js:58:15)
    at createPipeline (/usr/local/lib/node_modules/ledger-import/lib/filters/transactions/parse-transactions.js:22:24)
    at Object.parseTransactions (/usr/local/lib/node_modules/ledger-import/lib/filters/transactions/parse-transactions.js:34:18)
    at Import.run (/usr/local/lib/node_modules/ledger-import/lib/import.js:23:26)
    at Object.<anonymous> (/usr/local/lib/node_modules/ledger-import/bin/ledger-import:79:4)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)

**Comment by briviere** [comment]
This does not appear to be a problem anymore.

Thanks

Brian
